Repository Untoc-Web-Develop/Untoc-Front, pull requests merged in 2023-12, with the labels that each got.

#49 chore: tailwind 색상 코드 정리
  tailwind.config.js
Labels: Chore

#37 feat : 회원가입 페이지
  src/page/Register/Register.jsx
Labels: Feat

#55 Feature/tailwindcss sort plugin #51
  .prettierrc
  package-lock.json
  package.json
  src/components/Layouts/Header/Header.jsx
  src/components/Layouts/MainLayout.jsx
  src/components/Tab/StandardTab.jsx
Labels: Style, Chore

#44 Feature/게시판 페이지 #6
  src/page/BoardView/BoardView.jsx
  src/page/BoardWrite/BoardWrite.jsx
  src/routes/AppRouter.jsx
  src/routes/BoardRouter.jsx
Labels: Feat
