Repository Untoc-Web-Develop/Untoc-Front, pull requests merged in 2024-03, with the labels that each got.

#77 feat : 팀리스트 정보 페이지
  src/page/TeamListInfo/TeamListInfo.jsx
  src/routes/TeamListRouter.jsx
Labels: Feat

#84 design : 프로필 수정 페이지 반응형
  src/page/Profile/Edit/ProfileEdit.jsx
Labels: Design

#82 feat : 회원가입페이지 유효성 검사
  package-lock.json
  package.json
  src/page/Register/Register.jsx
Labels: Feat

#81 Feature/메인화면 information 레이아웃 설정 #30
  package-lock.json
  package.json
  public/index.html
  src/asset/main/background3.jpg
  src/asset/main/mainFriends.png
  src/asset/main/mainTeam.png
  src/components/ImgToolTip/ImgToolTip.jsx
  src/components/Layouts/MainLayout.jsx
  src/constant/devTerm.js
  src/page/Main/Main.jsx
  src/page/Main/MainInfo/MainInfo.jsx
  src/page/Main/MainInfo/components/RandomDevTerm.jsx
  tailwind.config.js
Labels: Feat, Design

#83 Feature/신입회원 모집 api #80
  src/api/applyApi.js
  src/api/index.js
  src/index.jsx
  src/page/Recruit/Recruit.jsx
  src/page/Recruit/RecruitDescription.jsx
  src/page/Recruit/RecruitForm.jsx
  src/page/Recruit/RecruitFormAdmin.jsx
  src/page/Recruit/RecruitFormUser.jsx
  src/page/Recruit/admin/RecruitAdmin.jsx
  src/page/Recruit/admin/RecruitDescriptionAdmin.jsx
  src/page/Recruit/admin/RecruitFormAdmin.jsx
  src/page/Recruit/user/RecruitDescriptionUser.jsx
  src/page/Recruit/user/RecruitFormUser.jsx
  src/page/Recruit/user/RecruitUser.jsx
Labels: Feat

#45 Feature/메인화면 activity 레이아웃 설정 #32
  package-lock.json
  package.json
  public/index.html
  src/components/ImgToolTip/ImgToolTip.jsx
  src/mocks/mainTeamTitles.jsx
  src/page/Main/Main.jsx
  src/page/Main/MainActivity/MainActivity.jsx
  src/page/Main/MainInfo/Component/BgCircle.jsx
  src/page/Main/MainInfo/MainInfo2.jsx
  tailwind.config.js
Labels: Feat

#78 feat : 팀리스트 빌딩 페이지
  package-lock.json
  package.json
  src/asset/teambuilddefault/teamBuildDefaultImg.png
  src/page/TeamListBuild/Dummy.jsx
  src/page/TeamListBuild/SelectMember.jsx
  src/page/TeamListBuild/TeamListBuild.jsx
  src/routes/TeamListRouter.jsx
Labels: Feat

#86 Refactor/신입회원 모집 api 수정 #85
  src/api/applyApi.js
  src/page/Recruit/admin/RecruitAdmin.jsx
  src/page/Recruit/user/RecruitDescriptionUser.jsx
  src/page/Recruit/user/RecruitFormUser.jsx
Labels: Refactor

#88 Featrue/미완성 라우터 제거 #87
  src/api/whitelistApi.js
  src/components/ImgToolTip/ImgToolTip.jsx
  src/page/Login/Login.jsx
  src/page/Main/Main.jsx
  src/page/Main/MainInfo/MainInfo.jsx
  src/page/Profile/Edit/ProfileEdit.jsx
  src/routes/AppRouter.jsx
Labels: Feat

#91 fix : 줄바꿈
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/page/Main/Main.jsx
  src/page/Recruit/user/RecruitDescriptionUser.jsx
  src/page/Recruit/user/RecruitFormUser.jsx
Labels: Fix

#93 Feature/HeaderTab_권한별_#92
  src/components/Layouts/Header/HeaderTab/HeaderTab.jsx
  src/constant/headerMenu.js
  src/store/reducers/userReducer.js
Labels: Fix

#96 Feature/신입회원 지원서 엑셀 다운로드 #95
  package-lock.json
  package.json
  src/components/Modals/AlertModal.jsx
  src/components/Modals/ConfirmModal.jsx
  src/components/Modals/Modal.jsx
  src/page/Admin/AdminManageNewUser/AdminManageNewUser.jsx
  src/page/Admin/AdminManageNewUser/components/ApplyForm.jsx
  src/page/Admin/AdminManageNewUser/newUserList.js
  src/page/Admin/components/AdminTab/AdminTab.jsx
  src/page/Admin/components/ControlBar/ControlBar.jsx
  src/page/Recruit/admin/RecruitDescriptionAdmin.jsx
  src/page/Recruit/admin/RecruitFormAdmin.jsx
  src/page/Recruit/user/RecruitDescriptionUser.jsx
  src/routes/AdminRouter.jsx
  src/routes/AppRouter.jsx
Labels: Feat

#97 신입회원 모집 페이지 임지 중단
  src/asset/recruit/sorryImg.png
  src/page/RecruitError/RecruitError.jsx
  src/routes/AppRouter.jsx
Labels: Feat

#98 feat : 상태 관리
  src/page/TeamListBuild/SelectMember.jsx
  src/page/TeamListBuild/TeamListBuild.jsx
  src/routes/AppRouter.jsx
Labels: Feat

#101 Feature/네트워킹 페이지 #100
  src/page/Network/Network.jsx
  src/page/Network/components/SearchConditionCard.jsx
  src/page/Network/components/SearchConditionSideBar.jsx
  src/page/Network/components/UserCard.jsx
  src/routes/AppRouter.jsx
Labels: Feat

#105 feat : 비밀번호 찾기 페이지
  src/page/FindPassword/FindPassword.jsx
  src/routes/AppRouter.jsx
Labels: Feat

#104 Feature/화이트리스트 #102
  src/api/whiteListApi.js
  src/page/Admin/WhiteList/WhiteList.jsx
  src/page/Admin/WhiteList/components/EnrollWhiteList.jsx
  src/page/Admin/WhiteList/components/ManageWhiteList.jsx
  src/page/Admin/WhiteList/components/WhiteListCard.jsx
  src/page/Admin/components/AdminTab/AdminTab.jsx
  src/routes/AdminRouter.jsx
Labels: Feat

#107 Feature/회원 관리 api #106
  src/api/adminApi.js
  src/page/Admin/AdminManageUser/AdminManageUser.jsx
  src/page/Admin/AdminManageUser/userList.js
  src/page/Admin/components/AdminTab/AdminTab.jsx
  src/routes/AdminRouter.jsx
  src/routes/AppRouter.jsx
Labels: Feat
